const username = [
  'skywalker123',
  'codingQueen',
  'javaNinja',
  'pythonic',
  'byteMe',
  'devDiva',
  'codeCrusader',
  'functionFanatic',
  'nullPointer',
  'syntaxSamurai',
  'bugHunter',
  'terminalWizard',
  'stackOverflow',
  'scriptKid',
  'frontendFury',
  'backendBoss',
  'cloudChaser',
  'dataDynamo',
  'apiArtisan',
  'devOpsDuke',
  'testTitan',
  'uiUnicorn',
  'cssSorcerer',
  'htmlHero',
  'jsonJuggler'
];

const emails = [
  'skywalker123@example.com',
  'codingQueen@example.com',
  'javaNinja@example.com',
  'pythonic@example.com',
  'byteMe@example.com',
  'devDiva@example.com',
  'codeCrusader@example.com',
  'functionFanatic@example.com',
  'nullPointer@example.com',
  'syntaxSamurai@example.com',
  'bugHunter@example.com',
  'terminalWizard@example.com',
  'stackOverflow@example.com',
  'scriptKid@example.com',
  'frontendFury@example.com',
  'backendBoss@example.com',
  'cloudChaser@example.com',
  'dataDynamo@example.com',
  'apiArtisan@example.com',
  'devOpsDuke@example.com',
  'testTitan@example.com',
  'uiUnicorn@example.com',
  'cssSorcerer@example.com',
  'htmlHero@example.com',
  'jsonJuggler@example.com'
];

// Export the functions for use in seed.js
module.exports = { username, emails };
