const username = [
  'skywalker123',
  'codingQueen',
  'javaNinja',
  'pythonic',
  'byteMe',
  'devDiva',
  'codeCrusader',
  'functionFanatic',
  'nullPointer',
  'syntaxSamurai',
  'bugHunter',
  'terminalWizard',
  'stackOverflow',
  'scriptKid',
  'frontendFury',
  'backendBoss',
  'cloudChaser',
  'dataDynamo',
  'apiArtisan',
  'devOpsDuke',
  'testTitan',
  'uiUnicorn',
  'cssSorcerer',
  'htmlHero',
  'jsonJuggler'
];

const emails = [
  'skywalker123@example.com',
  'codingQueen@example.com',
  'javaNinja@example.com',
  'pythonic@example.com',
  'byteMe@example.com',
  'devDiva@example.com',
  'codeCrusader@example.com',
  'functionFanatic@example.com',
  'nullPointer@example.com',
  'syntaxSamurai@example.com',
  'bugHunter@example.com',
  'terminalWizard@example.com',
  'stackOverflow@example.com',
  'scriptKid@example.com',
  'frontendFury@example.com',
  'backendBoss@example.com',
  'cloudChaser@example.com',
  'dataDynamo@example.com',
  'apiArtisan@example.com',
  'devOpsDuke@example.com',
  'testTitan@example.com',
  'uiUnicorn@example.com',
  'cssSorcerer@example.com',
  'htmlHero@example.com',
  'jsonJuggler@example.com'
];

const thoughts = [
  'Learning JavaScript is so much fun',
  'Just finished a new project, feeling accomplished.',
  'Debugging code can be so frustrating yet rewarding.',
  'Pair programming really helps me understand better.',
  'Front-end development is an art form.',
  'Back-end logic is like solving a puzzle.',
  'I love experimenting with new frameworks.',
  'Code reviews are essential for quality.',
  'Version control is a lifesaver.',
  'Clean code is the best code.',
  'Automated testing speeds up development.',
  'Continuous integration is a game changer.',
  'Deployment day always feels stressful.',
  'Refactoring code is like cleaning up a messy room.',
  'I can’t believe how far Ive come as a developer.',
  'Open source contributions are so rewarding.',
  'The community support in programming is amazing.',
  'I enjoy solving complex problems with simple solutions.',
  'Staying up to date with tech trends is crucial.',
  'APIs are the building blocks of modern web apps.',
  'Data structures and algorithms are fascinating.',
  'Cloud computing opens up so many possibilities.',
  'I love the challenge of optimizing performance.',
  'Security should always be a priority in development.',
  'Documenting code is just as important as writing it.'
];


// Export the functions for use in seed.js
module.exports = { username, emails, thoughts };
